BaSP-TG-56: controllers, model and postman collection update
BaSP-m2022/coco-trackgenix-server pull request #20
Opened 2022-05-21 18:13 UTC by ArianaMaldonado

**The following tickets were done in this PR:**

> - TG-51: updating model for tasks
> - TG-56: updating controllers for tasks
> - TG-53: linking Tasks collections (which was ignored because Tasks does not need it)

2022-05-21 20:33 UTC, lucasrendo requested changes
Put validation should be updated so that the client can update the worked hours on a task

2022-05-21 20:33 UTC, lucasrendo commented on src/controllers/tasks.js
Put method is not updated so neither workedHours or date can be modified (unless it's intentional)

2022-05-21 20:33 UTC, lucasrendo commented on src/validations/tasks.js
> +  workedHours: joi
i can use negative numbers and as many decimals as i want

2022-05-21 20:33 UTC, lucasrendo commented on src/validations/tasks.js
> +  date: joi
no need to validate this as it's set by the database with the current time, the client do not send any date to validate

2022-05-21 20:33 UTC, lucasrendo commented on src/validations/tasks.js
> +    description: req.body.description.toLowerCase().trim(),
to check for the description only is enough, as if i have 2 tasks with the exact same description it's considered to already exist, no need to also match existing worked hours and date

2022-05-22 14:01 UTC, lucasrendo approved these changes

2022-05-22 14:01 UTC, lucasrendo commented on src/controllers/tasks.js
>        targetTask.description = req.body.description.toLowerCase();
is this line necessary?

2022-05-22 15:53 UTC, EzeRocco approved these changes

2022-05-22 18:47 UTC, merged