Basp-tg-39 projects-day
BaSP-m2022/coco-trackgenix-server pull request #22
Opened 2022-05-23 13:40 UTC by dayanagm96

Updating controllers, models and validations form Projects.

2022-05-23 14:04 UTC, dayanagm96 commented on src/controllers/projects.js
>        data: allProjects,
That's not the actual response, that's from the populate method. A parameter to indicate mongoose the path to bring.

2022-05-23 15:15 UTC, lucasrendo requested changes
- No validations to check if the employee id provided in the request is a valid id, existing in the database
- Test files should not go in this PR
- It's necessary to change the ref to the employee model in the project schema

2022-05-24 01:16 UTC, lucianofrailelopez approved these changes

2022-05-24 01:45 UTC, lucasrendo approved these changes

2022-05-24 02:42 UTC, merged