BaSP-TG-58: Super-Admins
BaSP-m2022/coco-trackgenix-server pull request #27
Opened 2022-05-24 02:49 UTC by lucianofrailelopez

• GET (TG-58): tests for getAll and getById.  
• POST (TG-62): tests for creating a Super-Admins.  
• PUT (TG-65): tests for updating aSuper-Admins.  
• DELETE (TG-64): tests for deleting aSuper-Admins.

2022-05-24 03:27 UTC, ArianaMaldonado requested changes
There is no test for getById function.

2022-05-24 03:27 UTC, ArianaMaldonado commented on src/tests/super-admins.test.js
> +
There's no test for getById function

2022-05-24 03:27 UTC, ArianaMaldonado commented on src/tests/super-admins.test.js
> +//     test('Shold create an Super-Admin', async () => {
Be careful with the string inside `test()`, you wrote "shold" instead of "should".

2022-05-25 12:36 UTC, dayanagm96 approved these changes

2022-05-25 12:36 UTC, dayanagm96 commented on src/tests/super-admins.test.js
> +    expect(response.status).toBeTruthy();
If you are looking for a true error, the response should be 'response.error', no?

2022-05-25 12:36 UTC, dayanagm96 commented on src/tests/super-admins.test.js
> +  test('Should create an Super-Admin', async () => {
The description should be 'Should create _a_ Super-Admin'. Line 79 is the same.

2022-05-25 13:55 UTC, lucasrendo approved these changes

2022-05-25 13:55 UTC, lucasrendo commented on src/controllers/super-admins.js
> +    return res.status(400);
catch error should be 500 and contain te structure { msg, data, error}

2022-05-25 13:55 UTC, lucasrendo commented on src/controllers/super-admins.js
> +    return res.status(500);
response should contain json with { msg, data, error}

2022-05-25 13:55 UTC, lucasrendo commented on src/seeds/tasks-seeds.js
> +// }];
this should not be commented

2022-05-25 13:55 UTC, lucasrendo commented on src/tests/super-admins.test.js
> +    expect(response.status).toBe(400);
should check for undefined data as described on the test description

2022-05-25 13:55 UTC, lucasrendo commented on src/tests/super-admins.test.js
> +    expect(response.status).toBe(404);
should check for true error as for what the test says

2022-05-25 19:59 UTC, merged