TG-190: Update SUPERADMIN BE with new data model.
BaSP-m2022/coco-trackgenix-server pull request #39
Opened 2022-07-05 21:37 UTC by gregorioelias

- [x] TG-113: BUGS Report: SUPER-ADMIN.
- [x] TG-187: Update data model on SUPER-ADMIN entity.

For more specific information, read the trello ticket: https://trello.com/c/UpTs7iDc/190-update-superadmin-be-with-new-data-model

2022-07-06 03:25 UTC, marcomigliaro approved these changes

2022-07-06 03:25 UTC, marcomigliaro commented on src/models/Super-admins.js
> -  lastName: {
Shouldn´t have name and last name?

2022-07-06 06:58 UTC, SuarezAlexisEzequiel commented on src/models/Super-admins.js
>      maxlength: 20,
Maybe will better if we move out 'minlength' and 'maxlength' of the model, and keep it only in the validations

2022-07-06 06:59 UTC, SuarezAlexisEzequiel requested changes
Changes requested on models/Super-admins.js

2022-07-06 13:36 UTC, Lucas-DeLorenzi requested changes

2022-07-06 15:17 UTC, DeepFreq approved these changes

2022-07-06 17:19 UTC, marcomigliaro approved these changes

2022-07-06 18:10 UTC, SuarezAlexisEzequiel approved these changes

2022-07-07 23:36 UTC, Lucas-DeLorenzi approved these changes

2022-07-08 08:29 UTC, merged