BaSP-TG-160-115-191: Create and Update Endpoints - Employees BE
BaSP-m2022/coco-trackgenix-server pull request #40
Opened 2022-07-06 06:50 UTC by SuarezAlexisEzequiel

Done:
- TG-160: Create and Update endpoints - Employees BE [Ticket](https://trello.com/c/2mawbiyt/160-create-and-update-endpoints-employees-be)
```
1. Check if endopoints works well
2. Update it if necesary
3. Update middleware
```

- TG-115: BUGS Report: EMPLOYEE [Ticket](https://trello.com/c/dVh07iOt/115-bugs-report-employeel)
```
1. In the <employee> controllers, change the return messages in the json responses. Change "msg" to "message".
2. POST: Change message of create: "Status 200". Create a more specific and clear message. Example: "A new employee has been added successfully."
3. GET by id: Message is uninformative. Create a more specific and clear message. Example: "The employee with the ID has been found."
4. GET ALL: Change message: "Status 200". Create a more specific and clear message. Example: "Employees list displayed correctly."
5. PUT-Update: Change message of update employee: "Status 200". Create a more specific and clear message. Example: "The employee {{_id}} data has been updated correctly."
6. DELETE: Delete "Status 200:" of the success message. The change should be displayed as follows: "Employee with {{_id}} id was deleted". Remember to capitalize the first letter.
7. <CONTROLLERS-EMPLOYEE> Lines: From 45 to 50. Delete all comments.
```

- TG-191: Update EMPLOYEE BE with new data model [Ticket](https://trello.com/c/49axIDUC/191-update-employee-be-with-new-data-model)
```
1. Check that the entity schema follows the new data model. Update if necessary.
2. Modify controllers.
3. Modify validations.
4. Check that the changes work (Postman)
5. Do the changes required on TG-115
```

2022-07-06 14:28 UTC, Lucas-DeLorenzi requested changes

2022-07-06 14:28 UTC, Lucas-DeLorenzi commented on src/controllers/employees.js
>    try {
maybe it's possible to check if the id parameter exists and add the 400 error code option

2022-07-06 14:28 UTC, Lucas-DeLorenzi commented on src/controllers/employees.js
> +    return res.json({
missing error code. A necessary type of error code could be 401

2022-07-06 14:28 UTC, Lucas-DeLorenzi commented on src/controllers/employees.js
> +    const update = await Employee.findByIdAndUpdate(req.params.id, req.body, {
maybe it's possible to check if the id parameter exists and add  400 and 404 error codes options

2022-07-06 14:28 UTC, Lucas-DeLorenzi commented on src/validations/employees.js
>      password: Joi.string().min(3).max(30).required(),
it could have a regex that requires at least one number and one letter

2022-07-06 18:12 UTC, gregorioelias commented on src/validations/employees.js
> +      message: 'There was an error during the validation of the request',
Could be added data in the response.

2022-07-06 18:13 UTC, gregorioelias commented on src/validations/employees.js
> +      message: 'There was an error during the validation of the request',
Could be added data in the response.

2022-07-08 20:22 UTC, Lucas-DeLorenzi approved these changes

2022-07-10 01:09 UTC, gregorioelias approved these changes

2022-07-10 18:47 UTC, merged